#!/usr/bin/env zsh

set -e

# TODO convert to bash and check if parameters are set
# TODO help display

pushd "$DOTFILES"
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder
done
popd