#!/usr/bin/env bash

# TODO better solution would be global script, but autorandr doesn't seem to set global variables it should set.
# !!!! when changing something here, chances are, you want to reverse them in other profile hooks as well

# set dpi for most applications
sed -i -e 's/Xft.dpi: [0-9]*$/Xft.dpi: 144/g' "$HOME"/.Xresources

# force scaling of spotify, dpi scaling doesn't work
sed -i -e 's/Exec=spotify \%U/Exec=spotify --force-device-scale-factor=1.5 %U/g' \ 
    "$HOME"/.local/share/applications/spotify.desktop

xrandr --dpi 144

# restart polybar after switch
$HOME/.config/polybar/launch.sh &
